apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bpf-file-monitor
  namespace: becker
  labels:
    exp: ebpf
spec:
  selector:
    matchLabels:
      name: ebpf-monitoring
  template:
    metadata:
      labels:
        name: ebpf-monitoring
    spec:
      hostPID: true
      nodeSelector:
        exp: bpf
      containers:
        - name: cgroup-monitor
          image: srnbckr/cgroup-monitor:20.04
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "500Mi"
          securityContext:
            privileged: true
          volumeMounts:
            - name: tmp-results
              mountPath: /results
          args:
            - "--perfbuf"
            - "-O"
            - "/results/cgroups.csv"

        - name: bpf-monitor
          image: srnbckr/bpf-monitor:20.04
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "500Mi"
          securityContext:
            privileged: true
          volumeMounts:
            - name: host-kernel
              mountPath: /sys/kernel/debug
            - name: tmp-results
              mountPath: /results
          args:
            - "--perfbuf"
            - "--nofilter"
            - "-O"
            - "/results/file-bpf.csv"

        - name: pidfinder
          image: srnbckr/pidfinder
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "500Mi"
          securityContext:
            privileged: true

          volumeMounts:
            - name: tmp-results
              mountPath: /results
            - mountPath: /var/run 
              name: docker-sock 
          env:
            - name:  DOCKER_API_VERSION
              value: "1.35"
            - name: RESULT_PATH
              value: "/results"
    
      volumes:
        - name: host-kernel
          hostPath:
            path: /sys/kernel/debug
        - name: tmp-results
          hostPath:
            path: /tmp/results
        - name: docker-sock 
          hostPath: 
            path: /var/run 