apiVersion: v1
kind: Pod
metadata:
  name: nextflow-sleep-pod
  labels:
    app: nextflow-sleeper
spec:
  nodeSelector:
    exp: ebpf  # Ensures the pod is scheduled on nodes with this label
  securityContext:
    runAsUser: 0  # Run containers in the Pod as root user
  volumes:
    - name: workflow-monitoring-volume
      persistentVolumeClaim:
        claimName: workflow-monitoring-data
  containers:
  - name: nextflow
    image: nextflow/nextflow
    command: ["sleep"]
    args: ["infinity"]  # Runs sleep indefinitely
    volumeMounts:
      - name: workflow-monitoring-volume
        mountPath: "/workspace"

