apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebpf-pvc-test  # name of your claim
  namespace: becker # adjust to your own namespace: <username>
spec:
  storageClassName: cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10G # define the size of the volume
