apiVersion: v1
kind: Pod
metadata:
  name: cephfs-pod
  namespace: becker
spec:
  containers:
  - name: nfs1
    image: alpine:3.2
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    volumeMounts:
      - mountPath: /data
        name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: ebpf-pvc-test
