#FROM debian
FROM ubuntu:24.04
WORKDIR /
RUN apt update
ENV DEBIAN_FRONTEND=noninteractive

# to get the bcc code
RUN apt install -y git
# bcc dependencies
RUN apt install -y zip bison build-essential cmake flex git libedit-dev \
  libllvm18 llvm-18-dev libclang-18-dev python3 zlib1g-dev libelf-dev libfl-dev python3-setuptools \
  liblzma-dev libdebuginfod-dev arping netperf iperf libpolly-18-dev

RUN git clone -b v0.35.0 --single-branch --depth 1 https://github.com/iovisor/bcc.git && \
    cd bcc && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make && \
    make install && \
    cmake -DPYTHON_CMD=python3 .. && \
    cd src/python/ && \
    make && \
    make install && \
    cd / && \
    rm -rf /bcc

WORKDIR /bpf

COPY fileaccess.py .
COPY testdir ./testdir

COPY entrypoint-file.sh /
RUN chmod +x /entrypoint-file.sh
ENTRYPOINT [ "/entrypoint-file.sh" ]
